one's and expressions
22S-LGN-PS/programming-challenges pull request #32
Opened 2022-08-12 10:14 UTC by gracekim027

2022-08-12 23:39 UTC, lucetre requested changes

2022-08-12 23:39 UTC, lucetre commented on gracekim027/Expressions/Expressions.iml
> +<?xml version="1.0" encoding="UTF-8"?>
remove *.iml & add them in .gitignore

2022-08-12 23:39 UTC, lucetre commented on gracekim027/.idea/modules.xml
>      <modules>
ditto: ignore *.xml

2022-08-13 01:00 UTC, nick11967 commented on gracekim027/Ones/src/test.java
> +       while (flag && num != 1){
remove 'flag'
while( (p*10+1) % num != 0 )
remove if-else

2022-08-31 08:18 UTC, merged